version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-intolerables
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: intolerables
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
volumes:
  mysql_data:
