
version: '3'
services:
  libretranslate:
    image: libretranslate/libretranslate
    ports:
      - "5000:5000"
    volumes:
      - libretranslate-data:/app/data
    restart: unless-stopped

volumes:
  libretranslate-data:
